### ISSUE TITLE
Search SDK for iOS

### ISSUE THREAD

**Issue by sinisa503** [mapbox/search-ios-artifacts#1]
Hello!

I tried to install Search SDK thru Carthage with github "mapbox/search-ios-artifacts" ~> 1.0.0-beta"
and i got this error: "Dependency "search-ios-artifacts" has no shared framework schemes for any of the platforms: iOS".

**Comment by OdNairy** [comment]
Hi, Siniša. Thank you for opening the issue.
It is expected behavior as mapbox/search-ios-artifacts repo is designed to simplify the integration of MapboxSearch and MapboxSearchUI.
Technically, Carthage download and build dependencies correctly and even doesn't return an error to the shell.
